# GUI Data
Label.Browse = "Browse"
Tooltip.Browse = "Browse through images in the current folder"
Label.First = "First"
Tooltip.First = "Goto the first image in the current folder"
Label.Previous = "Previous"
Tooltip.Previous = "Goto the previous image in the current folder"
Label.Next = "Next"
Tooltip.Next = "Goto the next image in the current folder"
Label.Last = "Last"
Tooltip.Last = "Goto the last image in the current folder"
